config/routes.rb
Marketplace::Application.routes.draw do
  get "tags/index"
  resources :products do
    post 'remove'
  end

  devise_for :sellers, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }
  root "home#index"
  post 'home/set_currency', as: 'currency'

   resources :sellers do
     member do
       get 'show'
       get 'edit'
       put 'update', as: 'update'
     end
   end

end

app/models/color.rb
class Color < ActiveRecord::Base
  has_and_belongs_to_many :products
end

app/models/price.rb
class Price < ActiveRecord::Base
  belongs_to :product

  validates_presence_of [:amount, :currency]
  validates_inclusion_of :currency, in: %w(RUB USD EUR)
  validates_format_of :amount, with: /\A\d*\.\d{2,}\z/

  def exchange(target_currency='USD')
    currencies = [currency, target_currency]
    rate = case currencies
             when ["RUB", "EUR"]
               0.02
             when ["EUR", "RUB"]
               45.58
             when ["RUB", "USD"]
               0.03
             when ["USD", "RUB"]
               33.56
             when ["EUR", "USD"]
               1.36
             when ["USD", "EUR"]
               0.74
             when ["RUB", "RUB"], ["USD", "USD"], ["EUR", "EUR"]
               1
           end

    #"#{target_currency} #{(amount * rate).round(2)}"
    sprintf('%.2f', amount * rate)
  end

  class << self
    def biggest(currency)
      big = []
      all.each {|price| big << price.exchange(currency)}
      big.sort.last
      #all.map(&:exchange).sort.last
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :tags
  searchkick index_name: 'products'

  validates_presence_of [:name, :description, :company, :count, :picture]
  validates_numericality_of :count, only_integer: true

  def search_data
    {
        name: name,
        description: description,
        company: company,
        count: count,
        published: published,
        color_name: colors.map(&:name),
        size_name: sizes.map(&:name),
        tag_name: tags.map(&:name),
        tag_id: tags.map(&:id),
        price_amount_usd: price.exchange
    }
  end

  def should_index?
    published && price # only index published records
  end


  belongs_to :seller
  has_and_belongs_to_many :sizes
  has_and_belongs_to_many :colors
  has_one :price
  accepts_nested_attributes_for :sizes

  #validates_presence_of :sizes
  #validates_presence_of :colors
  #validates_presence_of :tags


  accepts_nested_attributes_for :colors
  accepts_nested_attributes_for :price

  has_attached_file :picture, :styles => {:medium => "300x300>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"

  def tag_list= value
    self.tags = value.split(",").map do |n|
      Tag.where(name: n.strip.capitalize!).first_or_create!
    end
  end

  def tag_list
    self.tags.join(',')
  end

  def tag_name_list
    self.tags.pluck(:name)
  end

end

app/models/seller.rb
class Seller < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable, :recoverable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :products
end

app/models/size.rb
class Size < ActiveRecord::Base
  has_and_belongs_to_many :products
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :products

  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SearchHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    seller_path(current_seller)
  end
  def after_sign_up_path_for(resource)
    seller_path(current_seller)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :default_currency, only: :index


  def index
    if params[:query].present?
      colors = params[:query][:colors].nil? ? Color.pluck(:name) : params[:query][:colors]
      sizes = params[:query][:sizes].nil? ? Size.pluck(:name) : params[:query][:sizes]
      tags = params[:query][:tags].empty? ? Tag.pluck(:id) : params[:query][:tags].split(',')
      price = calculate_price(session[:currency], params[:query][:price])
      @products = Product.search '*', where: {color_name: colors,
                                              size_name: sizes,
                                              tag_id: tags,
                                              price_amount_usd: price}

    else
      @products = Product.search '*'
    end
  end


  def set_currency
    session[:currency] = params[:currency]
  end

  def default_currency
    session[:currency] ||= "USD"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :remove]
  before_action :authorized?


  # GET /products
  # GET /products.json
  def index
    #@products = Product.all
    redirect_to root_path
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    @product.build_price
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)


    respond_to do |format|
      if @product.save
        format.html { redirect_to seller_path(current_seller), notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|

      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def remove
    @product.update_attributes({published: false})

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :description, :company, :count,
                                    :published, :picture, :tag_list, :seller_id, :price_attributes => [:amount, :currency],
                                    :color_ids => [], :size_ids => [], :tag_ids => [])
  end

  def authorized?
    unless current_seller
      redirect_to root_url
    end
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def show
  end

  def edit
  end

  def update
    if current_seller.update(seller_params)
      redirect_to current_seller, :flash => {:notice => 'Profile updated!'}
    else
      redirect_to edit_seller_path(current_seller), :flash => {:alert => current_seller.errors }
    end

  end

  def seller_params
    params.require(:seller).permit(:email, :phone)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    results = []
         Tag.all.each do |t|
           results << {"id" => t.id.to_s,"text" => t.name, "total" => Tag.all.count.to_s}
         end
    results.select! {|r| params[:q].downcase.to_regexp(:literal => true).match(r["text"].downcase)}
    respond_to do |format|
      format.json  { render :json => Kaminari.paginate_array(results).page(params[:page]).per(10).to_json }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_links
    if current_seller
      raw("<li>#{link_to "Logout", destroy_seller_session_path, method: :delete, :data => {:confirm => 'Are you sure?'}}</li>")
    else
      raw("<li>#{link_to "Login", new_seller_session_path} </li><li>#{link_to "Register", new_seller_registration_path}</li>")
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/home/index.html.erb
<div class="page-header"><h1>Welcome to the Marketplace!</h1></div>
<%= render 'products/index' %>
<%= content_for :seller_links do %>
  <% if current_seller %>
    <p><%= link_to 'My profile', seller_path(current_seller) %></p>
  <% end %>
<% end %>

app/views/home/set_currency.js.erb
$('.price').each(function () {
  var price = $(this).next(".next").html();
  $(this).html(to_currency(price));
  $('#hidden').text('<%= Price.biggest(params[:currency]) %>');
  $("#slider-range").slider({
    range: true,
    min: 0,
    max: (Number)($('#hidden').text()),
    step: 0.5,
    values: [ 0, (Number)($('#hidden').text())],
    slide: function (event, ui) {
      $("#amount").val((ui.values[ 0 ]).toFixed(2) + " - " + (ui.values[ 1 ]).toFixed(2));
    }
  });
  $("#amount").val(($("#slider-range").slider("values", 0)).toFixed(2) +
          " - " + ($("#slider-range").slider("values", 1)).toFixed(2));

});

$("select").select2({
  width: 'resolve'
});

function to_currency(price) {
  currency = "<%= params[:currency]%>";
  switch (currency) {
    case 'USD':
      return (Number)(price).toFixed(2);
    case 'RUB':
      return (price * 33.56).toFixed(2);
    case 'EUR':
      return (price * 0.74).toFixed(2);
  }
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Marketplace" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>

<div class="navbar navbar-fluid-top">
  <div class="navbar-inner">
    <div class="container-fluid">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Marketplace</a>

      <div class="container-fluid nav-collapse">
        <ul class="nav">
          <%= navbar_links %>
        </ul>
        <%= form_tag currency_path, class: 'navbar-search', id: 'currency_form', remote: true do %>
          <div class="form-group">
            <%= content_for :nav %>
          </div>
        <% end %>

      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <!--<ul class="nav nav-list">-->
        <!--<li class="nav-header">Sidebar</li>-->
        <% if current_seller %>
          <p><%= link_to "Add new product", new_product_path %></p>
          <%= content_for :seller_links %>
          <% else %>
        Hello, guest!
        <% end %>
        <!--</ul>-->
        <%= content_for :sidebar %>
      </div>
      <!--/.well -->
    </div>
    <!--/span-->
    <div class="span7">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>
  </div>
  <!--/row-->

  <footer>
    <p>&copy; Company 2014</p>
  </footer>

</div>
<!-- /container -->

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product, :html => { :multipart => true } ) do |f| %>

  <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <!--<div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>-->
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>

  <div class="field">
    <%= f.collection_select :color_ids, Color.all, :id, :name, {}, {:multiple => true} %>
    </div>
  <div class="field"><%= f.collection_select :size_ids, Size.all, :id, :name, {}, {:multiple => true} %>
    <!--<%= f.collection_select :tag_ids, Tag.all, :id, :name, {}, {:multiple => true} %>-->

  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %>
    <%= f.text_field :tag_list %>
  </div>
  <%= f.fields_for :price do |p| %>
    <div class="field">
        <%= p.label :amount, "Price (in 2 decimal format, eg.: '12.35')" %><br>
        <%= p.number_field :amount %>
        <%= p.select :currency, ['RUB', 'USD', 'EUR'] %>
    </div>
  <% end %>
  <%= f.hidden_field :seller_id, value: current_seller.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_index.html.erb
<% content_for :sidebar do %>

  <%= render 'products/search' %>

<% end %>

<table class="table table-striped" id="product_index">
  <thead>
  <tr>
    <th>Picture</th>
    <th>Name</th>
    <th>Description</th>
    <th>Company</th>
    <th>Number</th>
    <th>Price</th>
    <th>Tags</th>
    <th>Colors</th>
    <th>Sizes</th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>

    <tr id="<%= product.id %>">
      <td><%= image_tag product.picture.url(:thumb), class: "img-responsive" %>
        <% if current_seller && current_seller.id == product.seller_id %>
          <%= form_tag product_remove_path(product), remote: true do |f| %>
            <%= hidden_field_tag :id, product.id %>
            <%= submit_tag 'Remove', data: {confirm: 'Are you sure?'} %>
          <% end %>
        <% end %>
      </td>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.company %></td>
      <td><%= product.count %></td>
      <td><span class="price"><%= product.price.exchange(session[:currency]) %></span>
        <span class='next' style="display:none"><%= product.price.exchange %></span></td>
      <td>
        <% product.tag_name_list.each do |tag| %>
          <span class="label"><%= tag %></span>
        <% end %>
      </td>
      <td><%= select_tag "colors", options_from_collection_for_select(product.colors, "id", "name"), readonly: true, class: 'table_select2' %></td>
      <td><%= select_tag "sizes", options_from_collection_for_select(product.sizes, "id", "name"), readonly: true, class: 'table_select2' %></td>
      <td></td>
    </tr>

  <% end %>
  </tbody>
</table>

app/views/products/_search.html.erb
<%= form_tag root_path, class: 'form-inline', method: :get, turboboost: true do %>
  <div class="form-group">
    <!--<%= text_field_tag :query, params[:query], class: 'form-control' %>-->
    <p><label for="query_colors">Colors:</label></p>
    <%= select_tag 'query[colors]', options_from_collection_for_select(Color.all, "name", "name"), multiple: true, class: 'select2' %>
    <p><label for="query_sizes">Sizes:</label></p>
    <%= select_tag 'query[sizes]', options_from_collection_for_select(Size.all, "name", "name"), multiple: true, class: 'select2' %>
    <!--<%= select_tag 'query[price]', options_from_collection_for_select(Price.all, "amount", "amount") %>-->
    <p><label for="query_tags">Tags:</label></p>
    <%= hidden_field_tag 'query[tags]', '', class: 'select2', id: 'e7' %>
    <p><label for="amount">Price range:</label></p>

    <div id="hidden" style="display: none"><%= Price.biggest(session[:currency]) %></div>
    <p>
      <%= text_field_tag 'query[price]', nil, id: 'amount', readonly: 'readonly' %></p>
    <!--<%= hidden_field_tag 'price', nil, id: "price_to_search" %>-->
    <!--<input type="text" id="amount" disabled="disabled" name="query[price]">-->
    <p id="slider-range"></p>


    <%= submit_tag 'Search', class: "btn", id: 'submit' %>
    <% if params[:query].present? %>
      <%= link_to 'clear', root_path, id: 'clear' %>
    <% end %>
  </div>
<% end %>
<% content_for :nav do %>
  <%= select_tag 'currency', options_for_select(["USD", "EUR", "RUB"], session[:currency]), onchange: "$('#currency_form').submit();", class: 'select2', id: 'currency_select' %>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<!--<h1>Listing products</h1>-->

<table>
    <% @products.each do |product| %>
    <div class="well">


      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.company %></td>
        <td><%= product.count %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    </div>
    <% end %>
</table>

<br>

<!--<%= link_to 'New Product', new_product_path %>-->

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', seller_path(current_seller) %>

app/views/products/remove.js.erb
$("tr[id='<%= params[:id]%>']").remove();

app/views/products/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @product.company %>
</p>

<p>
  <strong>Count:</strong>
  <%= @product.count %>
</p>

<p>
  <strong>Published:</strong>
  <%= @product.published %>
</p>

<p>
  <%= image_tag @product.picture.url(:medium) %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/sellers/_form.html.erb
<%= form_for current_seller, url: update_seller_path(current_seller), method: :put do |f| %>
  <p><%= f.label :email %> <%= f.text_field :email %></p>
  <p><%= f.label :password %> <%= f.password_field :password %></p>
  <p><%= f.label :phone %> <%= f.phone_field :phone %></p>
  <%= f.submit 'Update' %>
<% end %>

app/views/sellers/edit.html.erb
<h1>Edit profile</h1>
<%= render 'form' %>
<%= link_to 'Back', seller_path(current_seller) %>
<%= content_for :seller_links do %>
  <p><%= link_to 'Home', root_path(current_seller) %></p>
<% end %>

app/views/sellers/show.html.erb
<h1>Profile</h1>
<div id='seller'>
  <table class="table">
    <tr>
      <th>Email</th>
      <td><%= current_seller.email %></td>
    </tr>
    <tr>
      <th>Phone</th>
      <td><%= current_seller.phone || '' %></td>
    </tr>
    <tr>
      <td><%= link_to 'Edit', edit_seller_path(current_seller) %></td>
      <td></td>
    </tr>
  </table>
</div>
<%= content_for :seller_links do %>
  <p><%= link_to 'Home', root_path(current_seller) %></p>
<% end %>